// Generated by Selenium IDE
package SeleniumSample;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("https://www.google.com/search?q=flowers&sca_esv=0aade082d29507cb&sxsrf=ACQVn0-3ViomaC3LRnMcWRv2G2108gokDg%3A1709535299758&source=hp&ei=Q3DlZdKJLJrq1e8Px-GU-AI&iflsig=ANes7DEAAAAAZeV-U3vMmBhzH4eaFGG19LIVb9XZLm8A&ved=0ahUKEwiSt5Wig9qEAxUadfUHHccwBS8Q4dUDCBU&uact=5&oq=flowers&gs_lp=Egdnd3Mtd2l6IgdmbG93ZXJzMgoQIxiABBiKBRgnMgsQABiABBiKBRiSAzILEAAYgAQYigUYkgMyChAAGIAEGIoFGEMyBRAAGIAEMgoQABiABBgUGIcCMgoQABiABBiKBRhDMgUQABiABDIKEAAYgAQYigUYQzIFEAAYgARIgT5QAFjrMnAEeACQAQCYAYEBoAGTCaoBAzMuOLgBA8gBAPgBAZgCD6AC0ArCAhAQLhjHARjRAxiABBiKBRgnwgIEECMYJ8ICDhAuGIAEGLEDGMcBGNEDwgINEAAYgAQYigUYQxixA8ICBxAjGLECGCfCAgcQABiABBgKmAMAkgcENC4xMQ&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1050, 840));
    {
      WebElement element = driver.findElement(By.linkText("Flower (disambiguation)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#rso > .MjjYud:nth-child(1) .LC20lb")).click();
  }
}
